version: "2.1"
services:
  rackerrank-solved:
    build: .
    command: ["/commands/run_local.sh"]
    container_name: rackerrank-solved
    env_file: variables.env
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/app
      - $HOME/go/pkg/mod:/go/pkg/mod
